{% set name = "pandas-stubs" %}
{% set version = "2.0.3.230814" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_stubs-{{ version }}.tar.gz
  sha256: 1d5cc09e36e3d9f9a1ed9dceae4e03eeb26d1b898dd769996925f784365c8769

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8
    - types-pytz >=2022.1.1
    - numpy >=1.24.3

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
